### ISSUE TITLE
You can win and lose at the same time in Bubble Warehouse (should be fixed now)

### ISSUE THREAD

**Issue by JanneNiemela** [pirjoritokangas/KuuraInTheGlobe#28]
You can get the "You win" message even though you have missed more than the allowed amount of items.

**Comment by t2yres00** [comment]
I didn't get timer to stop when broken defined number of items, but I updated TimerScript's and UI script's TextSwitcher codes so that winning action won't happen in losing game even if timer runs out. It is difficult to test but I got that happen once and yes it seemed to work.

**Comment by t2yres00** [comment]
Now I got timer to stop when broken defined number of items. I too fixed winning-and-losing-at-same-time bug little more.
